### ISSUE TITLE
Workspace should match vim runtime path

### ISSUE THREAD

**Issue by H4ppy-04** [Stoozy/vimcord#10]
The workspace in rich presence will change when editing a sub folder.

For example, if I have the project structure:
```
my_project [current directory]
└── src
    └── main.py  [the file being edited inside Vim]
``` 

instead of the workspace being the current directory, it will appear as `src`:

![image](https://github.com/Stoozy/vimcord/assets/101031214/d7e96748-c785-455e-ab8d-e23d18df8ba6)

And this is what it looks like from the perspective of Vim

![image](https://github.com/Stoozy/vimcord/assets/101031214/6fe69f70-bd32-403a-8980-881316ce69a5)

so you can see that the workspace is still `my_project` but that does not reflect the rich presence text

**Comment by Stoozy** [comment]
Hello and thanks for opening the issue. This should be a simple fix as I am currently trying to get the workspace directory from the current file open instead of running pwd as you did. I'll get to it asap.

**Comment by H4ppy-04** [comment]
> Hello and thanks for opening the issue. This should be a simple fix as I am currently trying to get the workspace directory from the current file open instead of running pwd as you did. I'll get to it asap.  

Initially I'm not sure that would work since the runtime path inside vim may change if a person chooses to work on another project, but doesn't bother to quit and launch vim from the new workspace directory

This issue seems to be here:

https://github.com/Stoozy/vimcord/blob/6e82b783bdd19be827b6c47696907ccc72ecb053/python3/vimcord/rpc.py#L29

**Comment by Stoozy** [comment]
> > Hello and thanks for opening the issue. This should be a simple fix as I am currently trying to get the workspace directory from the current file open instead of running pwd as you did. I'll get to it asap.  
> 
> Initially I'm not sure that would work since the runtime path inside vim may change if a person chooses to work on another project, but doesn't bother to quit and launch vim from the new workspace directory
> 
> This issue seems to be here:
> 
> https://github.com/Stoozy/vimcord/blob/6e82b783bdd19be827b6c47696907ccc72ecb053/python3/vimcord/rpc.py#L29
> 
> 

Yea, I suppose some sort of configuration on workspaces would be best but I'm not sure how that would work. I'll use pwd in the meantime.

**Comment by Stoozy** [comment]
Hey, sorry it took me a while. The issue should be fixed now, let me know if you have any more trouble :)

**Comment by H4ppy-04** [comment]
> Hey, sorry it took me a while. The issue should be fixed now, let me know if you have any more trouble :)

No worries, seems to be fixed now. I am considering making this a separate issue but it may be helpful to add a debugging system. For example, it is slightly inconvenient to see 'Discord is not open' when running vim. It might be better to log this as a message in the vim console.

This can be done natively in neovim, and for regular vim there already seems to be some suggested fixes: https://vi.stackexchange.com/questions/19919/how-can-i-log-debug-messages-without-blocking
