### ISSUE TITLE
Vim log messages without blocking

### ISSUE THREAD

**Issue by H4ppy-04** [Stoozy/vimcord#11]
> Hey, sorry it took me a while. The issue should be fixed now, let me know if you have any more trouble :)

No worries, seems to be fixed now. I am considering making this a separate issue but it may be helpful to add a debugging system. For example, it is slightly inconvenient to see 'Discord is not open' when running vim. It might be better to log this as a message in the vim console.

This can be done natively in neovim, and for regular vim there already seems to be some suggested fixes: https://vi.stackexchange.com/questions/19919/how-can-i-log-debug-messages-without-blocking

_Originally posted by @Trivoz in https://github.com/Stoozy/vimcord/issues/10#issuecomment-1876246462_

**Comment by Stoozy** [comment]
Sorry for the late response, the latest commit should fix this. I've used the function provided in the link you sent, so you can just run `:DebugStatus` to see the messages.
