### ISSUE TITLE
Is it available to add file type icons?

### ISSUE THREAD

**Issue by Block81838** [Stoozy/vimcord#3]

**Comment by Stoozy** [comment]
Yes, I can add that feature fairly easily, I just haven't gotten around to it.

**Comment by Block81838** [comment]
thanks

**Comment by Stoozy** [comment]
Yea, just finished with the icons, let me know if you want a specific one.

**Comment by Block81838** [comment]
The big image is the file type icon, small image is vim icon, that will be great
and add a idle image, if fn == idle, large_image = idle_image
If ext not in thumbnail, large_image = vim icon

**Comment by Block81838** [comment]
and there is a little bug that is I must create a file then, edit it, rpc will show himself. but if I use vim filename(new file), rpc won't show himself

**Comment by Stoozy** [comment]
I believe that's another event for unsaved new buffers. I'll implement that tomorrow.

**Comment by Block81838** [comment]
Thank you a lot

**Comment by Stoozy** [comment]
Done with support for unsaved new buffers. Let me know if you have any other issues.

**Comment by Block81838** [comment]
works well, thanks

**Comment by Block81838** [comment]
I got a new bug bro.
That is pypresence shows an error message when the discord is closed
[Error Video](https://drive.google.com/file/d/1ArHgoqXLC6W8aO0eEuY692G1qVoE5kII/view?usp=sharing)

![Screenshot_20201026173744](https://user-images.githubusercontent.com/22847876/97243049-ad0f2300-17b2-11eb-9bad-cee466560102.png)

**Comment by Stoozy** [comment]
Thanks for the report! Will get on that soon.

**Comment by Stoozy** [comment]
Hey, I am now trying to handle most of the errors that are being spit out. Can you update and see if the bug still occurs?

**Comment by Block81838** [comment]
works well, thanks
